Table User {
  id String [pk]
  email String [unique, not null]
  name String [not null]
}

Table Task {
  id String [pk]
  title String [not null]
  description String
  completed Boolean [not null, default: false]
  deadline DateTime
  priority Priority
  tags String[] [not null]
  workspaceId String [not null]
}

Table Event {
  id String [pk]
  title String [not null]
  description String
  start DateTime [not null]
  end DateTime [not null]
  tags String[] [not null]
  workspaceId String [not null]
}

Table Workspace {
  id String [pk]
  name String [not null]
  ownerId String [not null]
}

Table WorkspaceMember {
  id String [pk]
  role WorkspaceMemberRole [not null]
  userId String [not null]
  workspaceId String [not null]
}

Table TaskToUser {
  taskId String [not null, ref: > Task.id]
  assigneeId String [not null, ref: > User.id]
}

Table EventToUser {
  eventId String [not null, ref: > Event.id]
  attendeeId String [not null, ref: > User.id]
}

Table TaskDependency {
  parentId String [not null, ref: > Task.id]
  dependencyId String [not null, ref: > Task.id]
}

Enum Priority {
  LOW
  MEDIUM
  HIGH
}

Enum WorkspaceMemberRole {
  MANAGER
  MEMBER
  INVITED
}

Ref: Task.workspaceId > Workspace.id [delete: Cascade]

Ref: Event.workspaceId > Workspace.id [delete: Cascade]

Ref: Workspace.ownerId > User.id

Ref: WorkspaceMember.userId > User.id [delete: Cascade]

Ref: WorkspaceMember.workspaceId > Workspace.id [delete: Cascade]
