name: Run tests
on:
  pull_request:
  push:
  workflow_dispatch:

env:
  NODE_VERSION: 22
jobs:
  test-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: true
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Test DB
        env:
          NEON_POSTGRES_PRISMA_URL: 'postgres://prisma:password@localhost:54320/dev'
          NEON_DATABASE_URL_UNPOOLED: 'postgres://prisma:password@localhost:54320/dev'
        run: |
          pnpm db:start
          pnpm db:seed
          pnpm test
          pnpm db:stop
